server:
  port: 7000


spring:
  application:
    name: zzr-system
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.100.128:3306/apollo-demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zzr20010112
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages

  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.100.128
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: Zzr20010112
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  # 允许 bean 覆盖，将 feign 接口 合成一个
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enabled: false

## MyBatis-Plus配置
#mybatis-plus:
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapper-locations: classpath*:mapper/*Mapper.xml
#  # 搜索指定包别名
#  type-aliases-package: com.zzr.**.mapper
#  # 加载全局的配置文件
#  config-location: classpath:mybatis/mybatis-config.xml

# 开启SQL语句日志打印
logging:
  level:
    com.zzr.apollo.mapper: debug